plugins {
    id 'com.android.application' version '9.1.1'
}

android {
    namespace 'com.rahirebra.qusannoo'
    compileSdk 34

    defaultConfig {
        applicationId "com.rahirebra.qusannoo"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("../qusannoo.keystore")
            storePassword System.getenv("KS_PASS")
            keyAlias "qusannoo"
            keyPassword System.getenv("KEY_PASS")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
